config/routes.rb
Rails.application.routes.draw do

    mount ActionCable.server => '/cable'

    resources :connectors

    resources :covers

    get 'show_status' => 'status#show_status'
    get 'sorting/destroy_page' => 'upload_sorting#destroy_page'
    get 'show_cover_pages/(:id)' => 'covers#show_cover_pages'
    get 'upload_sorting/download_pdf/(:id)' => 'upload_sorting#download_pdf', :as => :download_pdf

    post 'scan_status' =>  'uploads#scan_status'
    post 'create_from_scanner_jpg' => 'uploads#create_from_scanner_jpg', :as => :create_from_scanner_jpg
    post 'create_from_upload' => 'uploads#create_from_upload'
    post 'upload_mobile' => 'uploads#create_from_mobile_jpg',:as => :upload_mobile
    post 'convert_status' =>  'uploads#convert_status'
    post 'convert_upload_preview_jpgs' =>  'uploads#convert_upload_preview_jpgs'
    post 'convert_upload_pdf' =>  'uploads#convert_upload_pdf'
    get 'cd_server_status_for_mobile' => 'uploads#cd_server_status_for_mobile',:as => :cd_server_status_for_mobile

    get 'pdf_doc/:id' => 'search#show_pdf_document', :as => :pdf_document
    get 'pdf/:id' => 'search#show_pdf_page', :as => :pdf_page
    get 'jpg/:id' => 'search#show_jpg_page', :as => :jpg_page
    get 'rtf/:id' => 'search#show_rtf', :as => :rtf
    get 'original/:id' => 'search#show_original', :as => :original
    get 'pin_document/:id' => 'search#pin_document', :as => :pin_document
    get 'unpin_document/:id' => 'search#unpin_document', :as => :unpin_document

    post 'add_page' => 'search#add_page'

    get 'search/' => 'search#search'
    get 'found/' => 'search#found'
    get 'show_document_pages/:id' => 'search#show_document_pages',:as => :show_document_pages

    post 'sort_pages' => 'documents#sort_pages'
    get 'documents/remove_page/:id' => 'documents#remove_page'
    get 'documents/destroy_page' => 'documents#destroy_page'
    get 'delete_documents' => 'documents#delete_documents'

    get 'status/clear' => 'status#clear'
    get 'status/start_conversion' => 'status#start_conversion'
    get 'trigger_backup' => 'status#trigger_backup'
    get 'status/try_to_connect' => 'status#try_to_connect'
    get 'search_doc_id' => 'documents#search_doc_id'
    get 'search_page_id' => 'documents#search_page_id'
    get 'search_archive' => 'documents#search_archive'
    get 'get_server_status' => 'status#get_server_status'
    post 'get_docbox_status' => 'status#get_docbox_status'

    post 'status_drb' => 'status#status_drb'

    get "scanners/scan_info"

    post 'start_scanner' => 'scanners#start_scanner'
    post 'start_scanner_from_hardware' => 'scanners#start_scanner_from_hardware'
    post 'start_copy_from_hardware' => 'scanners#start_copy_from_hardware'
    post 'scan_error' =>  'scanners#scan_error'
    post 'scan_info' =>  'scanners#scan_info'

    resources :folders
    resources :tags
    resources :upload_sorting
    resources :documents
    resources :status
    resources :uploads

    root :to => 'search#search'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :accept_all_params

  def search
    @current_keywords||= []
    @sort_mode||= :time
  end

  def found

    session[:search_results] = request.url
    session[:sort_mode]=params[:sort_mode]
    @sort_mode=params[:sort_mode].to_sym

    @current_keywords=params[:document].nil? ? []:params[:document][:keyword_list]

    @documents_removed=Document.where(status: Document::DOCUMENT_FROM_PAGE_REMOVED)
    @documents=Document.search_index(params[:q],@current_keywords, params[:page],@sort_mode)

    @q=params[:q]

    render :action => 'search'

end


  def pin_document
    document=Document.find(params[:id])
    document.create_pinned_document
    @page=document.cover_page
  end

  def unpin_document
    document=Document.find(params[:id])
    document.pinned_document.destroy
    @page=document.cover_page
  end

  ## add a page to the document via drag and drop (from search screen)
  def add_page
    drag_id=params[:drag_id][/\d+/].to_i
    drop_id=params[:drop_id][/\d+/].to_i #I get the new page

    @drag_page=Page.find(drag_id)
    @drop_page=Page.find(drop_id)

    @drag_page.add_to_document(@drop_page.document)
    @drop_page.reload
    return "404"
  end

  ### Show document PDF and RTF

  def show_rtf
    @page=Page.find(params[:id])
  end

  def show_pdf_page
    page=Page.find(params[:id])
    send_file(page.pdf_path, :filename => page.pretty_filename(:pdf),:type => 'application/pdf', :page => '1')
  end

  def show_pdf_document
    document=Document.find(params[:id])
    pdf=document.pdf_file
    send_file(pdf.path, :filename => document.pretty_filename,:type => 'application/pdf', :page => '1')
    pdf.close
  end

  def show_original
    page=Page.find(params[:id])
    data=File.read(page.path(:org))
     send_data( data, :filename => page.pretty_filename(:org),:type => page.mime_type, :page => '1' )
  end

  def show_document_pages
    @pages=Document.find(params[:id]).pages.limit(4)
  end

  def accept_all_params
    params.permit!
    response.headers['SameSite'] = 'Lax'
  end

end

app/helpers/search_helper.rb
module SearchHelper
  def search_class(page)
    doc=page.document
    result="preview"
    result=result+" new_document" if doc.removed?
    result=result+" no_delete" if (doc.no_delete? and not doc.pinned?)
    result=result+" more_pages" if doc.page_count>1
    result=result+" pinned" if (doc.pinned?)
#    result=result+" no_backup" unless doc.backup?
    return result
  end
end

app/views/search/_keywords.html.erb
<!-- https://lokesh-coder.github.io/pretty-checkbox/ -->
<div id="keywords" class="line_break" >

    <% Tag.all.each do |tag| %>

          <div class="pretty p-default p-curve" style="float:left;min-width:70px;margin-top: 10px;">
          <%= check_box_tag("document[keyword_list][]", tag.id, current_keywords.include?(tag.id)) %>
            <div class="state p-warning"> <label><%= tag.name %>  </label></div>
          </div>

    <% end %>
    <div class="clear"></div>

</div>

app/views/search/_links_page_search.html.erb
<!-- will be yielded into /pages/show_page -->

<% if page.document.complete_pdf? %>
  |  <%= link_to("PDF", pdf_document_path(page.document.id)) %>
  <% if page.document_pages_count == 1 and page.mime_type != 'application/pdf' %>
  |  <%= link_to("   #{page.short_mime_type}", original_path(page.id)) %>
  <% end %>
<% else %>
 | <%= link_to("   #{page.short_mime_type}", original_path(page.id)) %>
<% end %>


<div style="float:right;">

   <%= link_to "Pin",pin_document_path(page.document.id),:remote => true unless page.document.pinned?  or page.document.removed?%>
    <%= link_to "Un-Pin ",unpin_document_path(page.document.id),:remote => true if page.document.pinned? %>

|  <%= link_to '  Details', edit_document_path(page.document.id) %>
|  <%= link_to('  Show', show_document_pages_path(page.document.id), :class => "link_show_pages", :remote => true) if page.document.page_count > 1 %>
  <a class='close_pages_link' style="display: none;">Close</a>
</div>

app/views/search/_page.html.erb
<% sd = '' %>
<% sd = "search_draggable" if (page.document_pages_count == 1 and (not page.document.no_delete?)) %>
<div class= '<%= "search_droppable #{sd}"%>' id='<%= page.id.to_s %>'>
    <div class='<%= search_class(page) %>' id='<%= 'page_' + page.id.to_s %>'>
    <%= render :partial => 'links_page_search', :layout => '/show_page', :locals => {:page => page} %>
  </div>
</div>

app/views/search/_show_document_pages.html.erb
<div id="show_document_pages" xmlns="http://www.w3.org/1999/html">
  <%  @pages.each do |page| %>
      <div class="show_single_page">
      <%= image_tag(page.short_path(:s_jpg), :id => page.id, :bigjpg => page.short_path(:jpg), :class => 'clickzoom') %>

      <div class="clear"></div>

      <div class="preview_footer">

       <%= "Page #{page.position+1}" %>  <%= "#{page.id} - #{page.created_at.strftime("%d.%m.%y")} - #{page.source}" %> |

      </div>
      </div>
  <%end%>
  <div class="clear"></div>
  <a id='close_pages'>Close</a>
</div>

app/views/search/_show_month_page.html.erb
<!-- Standard Template to show pages - with yield -->
<!-- http://railsonedge.blogspot.de/2008/04/dry-up-your-views-with-layouts-for-your.html-->

<div class="preview">
<%= image_tag('month.jpg') %>


  <div style="position:relative;left:30px;top:-290px;font-size: 32px;">
    <%= Date::MONTHNAMES[month]%>
  </div>

  <div style="position:relative;left:30px;top:-280px;font-size: 32px;">
    <%= year %>
  </div>


</div>

app/views/search/add_page.js.erb
// called when a single page is dropped to existing pages
$("#<%=@drag_page.id%>").remove();
$("#<%=@drop_page.id%>").replaceWith("<%= escape_javascript(render :partial => 'page', :locals => {:page => @drop_page}) %>");
RefreshPages()

app/views/search/pin_document.js.erb
$("#search_pinned").prepend("<%= escape_javascript(render :partial => 'page', :locals => {:page => @page}) %>");
$('#search_results').find("#page_<%=@page.id%>").addClass('pinned')
RefreshPages();

app/views/search/search.html.erb
<%= javascript_pack_tag "touch-punch" %>
<%= javascript_pack_tag "search" %>
<%= javascript_pack_tag "clickzoom" %>


<%= form_tag('/found', :method => "get", :class => "input_area") do %>

  <%= text_field_tag(:q, @q, :size => 40, :id => 'search_input') %>

  <span style="margin-left: 20px; font-size: large;">
<div class="pretty p-default p-curve">
  <%= radio_button_tag 'sort_mode', 'time', @sort_mode == :time %>
  <div class="state p-warning"> <label>Time</label> </div>
    </div>

      <div class="pretty p-default p-curve">
   <%= radio_button_tag 'sort_mode', 'relevance', @sort_mode == :relevance %>
        <div class="state p-warning"> <label>Relevance</label> </div>
 </div>


    </span>

  <%= render :partial => 'keywords', :locals => {:current_keywords => @current_keywords} %>

  <p class='submit'> <%= submit_tag "Search" , class: 'top_search_button' %></p>
<% end %>

<div id="search_pinned" %>
  <% PinnedDocument.all.each do |pd| %>
    <%= render :partial => 'page', :locals => {:page => pd.document.cover_page} %>
  <% end %>
</div>


<div id="search_removed"%>
<% unless @documents_removed.nil? then %>
  <% @documents_removed.each do |doc| %>
    <%= render :partial => 'page', :locals => {:page => doc.cover_page} %>
  <% end %>
<% end %>
</div>


<div id="search_results"%>
<% unless @documents.nil? then %>
  <% current_month = 0; current_year = 1900 %>
  <% @documents.each do |doc| %>
    <% p_month = doc.created_at.month; p_year = doc.created_at.year %>
    <% if @sort_mode == :time and (current_month != p_month or current_year != p_year) then %>
      <% current_month = p_month; current_year = p_year %>
      <%= render :partial => 'show_month_page', :locals => {:month => current_month, :year => current_year} %>
    <% end %>

    <%= render :partial => 'page', :locals => {:page => doc.cover_page} %>

  <% end %>
<% end %>
</div>
<div style="clear:both;"></div>

<%= will_paginate @documents unless @documents.nil? %>

app/views/search/show_document_pages.js.erb
$("#container").append("<%= escape_javascript(render('show_document_pages', :locals => { :document => @document})) %>");
$(".link_show_pages").hide();
$(".close_pages_link").show();

$('#show_document_pages').css('margin-left',<%=-(@pages.count * 360)/2 %>);

// This is the close link in the pop up window

$('#close_pages').click(function() {
    $('#show_document_pages').remove();
    $(".link_show_pages").show();
    $(".close_pages_link").hide()
});

// This is the close link visible in the search screen

$('.close_pages_link').click(function() {
    $('#show_document_pages').remove();
    $(".link_show_pages").show();
    $(".close_pages_link").hide()
});

app/views/search/show_rtf.html.erb
<%=link_to "<<<Back",:back, :style=>"font-size:15px;" %>
<div class="input_area" style="white-space: pre; font-family: monospace;    font-size: 12px; ">

  <%= @page.content%>
</div>

app/views/search/unpin_document.js.erb
$('#search_results').find("#page_<%=@page.id%>.pinned").parent().replaceWith("<%= escape_javascript(render :partial => 'page', :locals => {:page => @page}) %>");
$('#search_pinned').find("#page_<%=@page.id%>.pinned").remove()
RefreshPages()