config/routes.rb
Rails.application.routes.draw do

    mount ActionCable.server => '/cable'

    resources :connectors

    resources :covers

    get 'show_status' => 'status#show_status'
    get 'sorting/destroy_page' => 'upload_sorting#destroy_page'
    get 'show_cover_pages/(:id)' => 'covers#show_cover_pages'
    get 'upload_sorting/download_pdf/(:id)' => 'upload_sorting#download_pdf', :as => :download_pdf

    post 'scan_status' =>  'uploads#scan_status'
    post 'create_from_scanner_jpg' => 'uploads#create_from_scanner_jpg', :as => :create_from_scanner_jpg
    post 'create_from_upload' => 'uploads#create_from_upload'
    post 'upload_mobile' => 'uploads#create_from_mobile_jpg',:as => :upload_mobile
    post 'convert_status' =>  'uploads#convert_status'
    post 'convert_upload_preview_jpgs' =>  'uploads#convert_upload_preview_jpgs'
    post 'convert_upload_pdf' =>  'uploads#convert_upload_pdf'
    get 'cd_server_status_for_mobile' => 'uploads#cd_server_status_for_mobile',:as => :cd_server_status_for_mobile

    get 'pdf_doc/:id' => 'search#show_pdf_document', :as => :pdf_document
    get 'pdf/:id' => 'search#show_pdf_page', :as => :pdf_page
    get 'jpg/:id' => 'search#show_jpg_page', :as => :jpg_page
    get 'rtf/:id' => 'search#show_rtf', :as => :rtf
    get 'original/:id' => 'search#show_original', :as => :original
    get 'pin_document/:id' => 'search#pin_document', :as => :pin_document
    get 'unpin_document/:id' => 'search#unpin_document', :as => :unpin_document

    post 'add_page' => 'search#add_page'

    get 'search/' => 'search#search'
    get 'found/' => 'search#found'
    get 'show_document_pages/:id' => 'search#show_document_pages',:as => :show_document_pages

    post 'sort_pages' => 'documents#sort_pages'
    get 'documents/remove_page/:id' => 'documents#remove_page'
    get 'documents/destroy_page' => 'documents#destroy_page'
    get 'delete_documents' => 'documents#delete_documents'

    get 'status/clear' => 'status#clear'
    get 'status/start_conversion' => 'status#start_conversion'
    get 'trigger_backup' => 'status#trigger_backup'
    get 'status/try_to_connect' => 'status#try_to_connect'
    get 'search_doc_id' => 'documents#search_doc_id'
    get 'search_page_id' => 'documents#search_page_id'
    get 'search_archive' => 'documents#search_archive'
    get 'get_server_status' => 'status#get_server_status'
    post 'get_docbox_status' => 'status#get_docbox_status'

    post 'status_drb' => 'status#status_drb'

    get "scanners/scan_info"

    post 'start_scanner' => 'scanners#start_scanner'
    post 'start_scanner_from_hardware' => 'scanners#start_scanner_from_hardware'
    post 'start_copy_from_hardware' => 'scanners#start_copy_from_hardware'
    post 'scan_error' =>  'scanners#scan_error'
    post 'scan_info' =>  'scanners#scan_info'

    resources :folders
    resources :tags
    resources :upload_sorting
    resources :documents
    resources :status
    resources :uploads

    root :to => 'search#search'

end

app/models/document.rb
class Document < ActiveRecord::Base

  require 'tempfile'

  ThinkingSphinx::Callbacks.append(
      self, :behaviours => [:sql, :deltas]
  )


  has_many :pages, -> { order :position }, dependent: :destroy
  belongs_to :folder, optional: true
  belongs_to :cover, optional: true
  has_one :pinned_document,  dependent: :destroy


  accepts_nested_attributes_for :pages, :allow_destroy => true
  acts_as_taggable_on :keywords

  before_save :update_expiration_date
  before_destroy :check_no_delete

  #### Status
  DOCUMENT = 0 ##document was created based on an uploaded document
  DOCUMENT_FROM_PAGE_REMOVED = 1 ##document was created, as a page was removed from an existing doc
  DOCUMENT_NOT_ARCHIVED = 2


  ########################################################################################################

  def self.search_index(search_string, keywords, page_no, sort_mode)
    ###https://groups.google.com/forum/?fromgroups=#!msg/thinking-sphinx/WvOTN6NABN0/vzKnhx5CIvAJ

    search_config = {:page => page_no, :per_page => 30, :star => true}

    search_config.merge!({:with => {:tags => keywords.map! { |e| e.to_i }}}) unless keywords.empty?
    search_config.merge!({:order => "created_at desc, id DESC"}) if sort_mode == :time

    documents = Document.search(search_string, search_config)

    Rails.logger.info  "Document ******************************************"
    Rails.logger.info  "SearchConfig: #{search_config}"
    Rails.logger.info  "SearchString: #{search_string}"
    Rails.logger.info  "***************************************************"

    return documents

  end

  def cover_page
    self.pages.where(position: 0).first
  end


  def pdf_file

    docs = ''; self.pages.each { |p| docs += ' ' + p.pdf_path }
    pdf = Tempfile.new(["cd_#{self.id}", ".pdf"])

    #  if pdftk is not available for OS, you can use java_itext instead
    #  java_merge_pdf = "java -classpath './SupportFiles/java_itext/.:./java_itext/itext-5.3.5/*' MergePDF"   # java itext

    java_merge_pdf = "pdftk #{docs} cat output #{pdf.path}"
    Rails.logger.info  "PDF_FILE, merging PDF with pdftk and command: #{java_merge_pdf}"
    res = %x[#{java_merge_pdf}]
    return pdf
  end

  def backup?
    self.pages.where("backup = 0").count == 0
  end

  def pinned?
    self .pinned_document.present?
  end

  def removed?
    self.status==Document::DOCUMENT_FROM_PAGE_REMOVED
  end

  def update_after_page_change
    self.page_count = self.pages.count

    if self.page_count == 0
      self.destroy
    else

      ### if documents has pages with non-pdf-mime type, no complete PDF page can be generated
      if self.pages.where("pdf_exists=false").count > 0
        self.complete_pdf = false
      else
        self.complete_pdf = true
      end

      self.save!
    end
  end


  def check_no_delete
    if self.no_delete?
      Log.write_error('MAJOR ERROR', "System tried to delete -NO_DELETE- document with id:#{self.id}")
      raise "ERROR: System tried to delete -NO_DELETE- document with id:#{self.id}"
    end
  end

  # a summary page can only be displayed
  def show_summary_page?
    return true if (self.no_complete_pdf == false or self.page_count == 1)
    return false
  end

  def pretty_filename
    if cover_page.source == Page::PAGE_SOURCE_UPLOADED
      File.basename(cover_page.original_filename) + ".pdf"
    elsif comment.length > 0
      comment[0, 20].gsub(" ", "_").gsub('ä', 'a').gsub('ö', 'o').gsub('ü', 'u').chars.select(&:ascii_only?).join + ".pdf"
    else
      "docbox_d#{id}_p#{cover_page.id}_#{created_at.strftime("%Y%m%d")}" + ".pdf"
    end

  end

  private

  ##http://stackoverflow.com/questions/4902804/using-delta-indexes-for-associations-in-thinking-sphinx



  def update_expiration_date
    self.delete_at = nil if self.delete_at == Date.new(3000) #to allow reset the date back to null (newer expire)
  end

  ### https://github.com/mperham/sidekiq/blob/master/examples/clockwork.rb


end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :accept_all_params
  skip_before_action :verify_authenticity_token

  # GET /documents/1/edit
  def edit
    @document = Document.includes(:pages).find(params[:id])
  end

  def index
    @docs = Document.where('delete_at is not null').order('delete_at asc')

  end

  def update

    # check for cancel first

    @document = Document.find(params[:id])
    last_page = false

    if params[:name_upl].nil?

      Document.transaction do

        @document.status = Document::DOCUMENT if @document.status == Document::DOCUMENT_FROM_PAGE_REMOVED #document was changed by user
        @document.update(params[:document])
        @document.save

        # Sort pages based on order

        params[:order_pages].each_with_index do |page_id, position|
          page = Page.find(page_id)
          page.position = position
          page.save!
        end unless params[:order_pages].nil?

        # Delete pages
        params[:delete_pages].each do |page_id|
          last_page = Page.find(page_id).destroy_with_file
        end unless params[:delete_pages].nil?

        # Remove pages
        params[:remove_pages].each do |page_id|
          Page.find(page_id).move_to_new_document
        end unless params[:remove_pages].nil?

      end

    end
    if session[:search_results].nil?
      redirect_to root_url
    elsif last_page
      redirect_to session[:search_results]
    else
      redirect_to session[:search_results] + "#page_#{@document.pages.first.id}", :notice => "Successfully updated doc."
    end

  end

  def destroy_page
    @page = Page.find(params[:id])
    @page.destroy_with_file

    respond_to do |format|
      format.html { redirect_to search_url }
      format.js {}
    end

  end

  ################################### non HABTM ################################################


  ### UPDATE Document

  ## remove a page from the document via the edit action
  def remove_page
    @page = Page.find(params[:id])
    @document = @page.document

    @page.move_to_new_document

  end

  ### called in update document when the document is re-ordered
  def sort_pages
    params[:page].each_with_index do |page_id, position|
      page = Page.find(page_id)
      page.position = position
      page.save!
    end

    head :ok
  end

  ##### Maintain Pages

  def search_doc_id

    doc = Document.find(params[:q])
    if doc.nil? then
      flash[:error] = "Document not found"
      redirect_to :action => 'index'
    else
      redirect_to edit_document_url(doc.id)
    end
  end

  def search_page_id

    page = Page.find(params[:q])
    if page.nil?
      flash[:error] = "Page not found"
      redirect_to :action => 'index'
      return true
    end

    doc = page.document
    if doc.nil?
      flash[:error] = "Page found, but no document"
      redirect_to :action => 'index'
      return true
    end

    redirect_to edit_document_url(doc.id)

  end

  def delete_documents
    flash[:notice] = "Deleting documents end of lifecycle triggered"
    RemoveFromArchiveJob.perform_async
    redirect_to :action => 'index'
  end

  def search_archive
  end

  def accept_all_params
    params.permit!
  end


end

app/views/documents/_links_page_edit.html.erb
<!-- will be yielded into /pages/show_page -->

<!-- will be yielded into /pages/show_page -->

|
<%= link_to(page.short_mime_type, original_path(page.id))%>

<% if  page.mime_type!='application/pdf'%>
  |
  <%= link_to("PDF", pdf_page_path(page.id)) %>
<%end%>



<div style="float:right;" >
<%=  link_to "Delete",nil, class:'delete_link action_link', id:page.id unless page.document.no_delete? %>
<%= link_to "Remove",nil, class:'remove_link action_link',id:page.id if page.document_pages_count>1 %>
  </div>

app/views/documents/_pages_edit.html.erb
<ul class="doc_sort_list">
  <% document.pages.each do |page| %>
      <li id=<%= 'page_'+page.id.to_s %> draggable="true" class="sortable">
        <div class='preview prevent_drag'>
          <%= render :partial => "links_page_edit", :layout => '/show_page', :locals => {:page => page} %>
        </div>
        <input type='hidden' name='order_pages[]' value=<%= page.id %>/>
      </li>
  <% end %>
</ul>

app/views/documents/destroy_page.js.erb
$("#page_<%=@page.id%>").fadeOut('slow', function () {
    $(".doc_sort_list").html("<%= escape_javascript(render(:partial => 'pages_edit', :locals => { :document => @page.document})) %>");
});

app/views/documents/edit.html.erb
<%= javascript_pack_tag "documents_edit" %>
<%= javascript_pack_tag "clickzoom" %>
<%= javascript_pack_tag "delete_no_logic" %>
<%= javascript_pack_tag "touch-punch" %>




<div style="padding-left: 10px; font-size: large">
  <%= link_to("View full PDF Document", pdf_document_path(@document)) if @document.complete_pdf? %>
</div>

<%= form_for(@document) do |f| %>

  <div class="input_area form-inline" style='display:block;'>
    Comment:  <%= f.text_field :comment %>

    <label>
      Created:  <%= f.text_field "created_at", :value => @document.created_at.to_s, data: {behavior: "flatpickr"}, size: 8 %></label>
    <label>Folder: <%= f.select(:folder_id, Folder.all.collect { |f| [f.name, f.id] }) %> </label>
    <label>
      <%= if @document.delete_at.nil? then
            "Document will never expire"
          else
            "Document will expire in #{(@document.delete_at.year * 12 + @document.delete_at.month) - (Date.today.year * 12 + Date.today.month)} months"
          end %>
      | Expires :

      <%= f.date_select(:delete_at, {start_year: Date.today.year, order: [:year], include_blank: true}, {:id => 'lb_no_delete'}) %>

    </label>


    <label style="margin-left:10px">
      <div class="pretty p-default p-curve">
        <%= f.check_box(:no_delete, :id => 'cb_no_delete') %>
        <div class="state p-warning"> <label>Never delete this file</label></div>
      </div>
    </label>


    <label>
      <%= "Document(#{@document.id}) was created in #{@document.created_at.strftime('%B %Y')} for folder '#{@document.folder.short_name}'" %>
      <%= @document.pages.first.status_text %>
    </label>


    <%= render :partial => '/keywords', :locals => {:current_keywords => @document.keyword_ids} %>


    <br/>
    <%= f.submit "Cancel", :id => "id_upload_btn", :name => "name_upl" %>
    <%= f.submit "Update" %>

  </div>

  <h1>Adjust page order with drag and drop"</h1>

  <div style='float: left;width: 100%'>
    <%= render :partial => 'pages_edit', :locals => {:document => @document} %>
  </div>


<% end %>

app/views/documents/index.html.erb
<h1 style="color: green" id="notice"><%= flash[:notice] %></h1>
<h1 style="color: red" id="error"><%= flash[:error] %></h1>

<h1>Document by ID</h1>
<div class="status_frame">
  <%= form_tag("/search_doc_id", method: "get") do %>
      <%= label_tag(:q, "Search:") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
  <% end %>
</div>
<h1>Page by ID</h1>
<div class="status_frame">
  <%= form_tag("/search_page_id", method: "get") do %>
      <%= label_tag(:q, "Search:") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
  <% end %>
</div>

<h1>Documents to be deleted (end of livecycle)</h1>

<% if @docs.count==0 %>
    <h1>No documents to be deleted  !!</h1>
<% else %>

        <div class="status_frame">

          <%= button_to ">> DELETE NOW <<", delete_documents_path,:method => :get %>
</br>

      <table>
        <tr>
          <th>Document ID</th>
          <th>Comment</th>
          <th>Delete on</th>
          <th>!!Delete this run!!</th>
          <th></th>
        </tr>
        <% for doc in @docs %>
            <tr>
              <td><%= doc.id %></td>
              <td><%= doc.comment %></td>
              <td><%= doc.delete_at.strftime("%d.%m.%Y") %></td>
              <td><%= '!!!DELETE!!!' if Date.today > doc.delete_at %></td>
              <td><%= link_to "Edit", edit_document_path(doc) %></td>
            </tr>
        <% end %>
      </table>
    </div>
<% end %>

app/views/documents/remove_page.js.erb
$("#page_<%=@page.id%>").fadeOut('slow', function () {
    $(".doc_sort_list").html("<%= escape_javascript(render(:partial => 'pages_edit', :locals => { :document => @document})) %>");
});