config/routes.rb
Rails.application.routes.draw do

    mount ActionCable.server => '/cable'

    resources :connectors

    resources :covers

    get 'show_status' => 'status#show_status'
    get 'sorting/destroy_page' => 'upload_sorting#destroy_page'
    get 'show_cover_pages/(:id)' => 'covers#show_cover_pages'
    get 'upload_sorting/download_pdf/(:id)' => 'upload_sorting#download_pdf', :as => :download_pdf

    post 'scan_status' =>  'uploads#scan_status'
    post 'create_from_scanner_jpg' => 'uploads#create_from_scanner_jpg', :as => :create_from_scanner_jpg
    post 'create_from_upload' => 'uploads#create_from_upload'
    post 'upload_mobile' => 'uploads#create_from_mobile_jpg',:as => :upload_mobile
    post 'convert_status' =>  'uploads#convert_status'
    post 'convert_upload_preview_jpgs' =>  'uploads#convert_upload_preview_jpgs'
    post 'convert_upload_pdf' =>  'uploads#convert_upload_pdf'
    get 'cd_server_status_for_mobile' => 'uploads#cd_server_status_for_mobile',:as => :cd_server_status_for_mobile

    get 'pdf_doc/:id' => 'search#show_pdf_document', :as => :pdf_document
    get 'pdf/:id' => 'search#show_pdf_page', :as => :pdf_page
    get 'jpg/:id' => 'search#show_jpg_page', :as => :jpg_page
    get 'rtf/:id' => 'search#show_rtf', :as => :rtf
    get 'original/:id' => 'search#show_original', :as => :original
    get 'pin_document/:id' => 'search#pin_document', :as => :pin_document
    get 'unpin_document/:id' => 'search#unpin_document', :as => :unpin_document

    post 'add_page' => 'search#add_page'

    get 'search/' => 'search#search'
    get 'found/' => 'search#found'
    get 'show_document_pages/:id' => 'search#show_document_pages',:as => :show_document_pages

    post 'sort_pages' => 'documents#sort_pages'
    get 'documents/remove_page/:id' => 'documents#remove_page'
    get 'documents/destroy_page' => 'documents#destroy_page'
    get 'delete_documents' => 'documents#delete_documents'

    get 'status/clear' => 'status#clear'
    get 'status/start_conversion' => 'status#start_conversion'
    get 'trigger_backup' => 'status#trigger_backup'
    get 'status/try_to_connect' => 'status#try_to_connect'
    get 'search_doc_id' => 'documents#search_doc_id'
    get 'search_page_id' => 'documents#search_page_id'
    get 'search_archive' => 'documents#search_archive'
    get 'get_server_status' => 'status#get_server_status'
    post 'get_docbox_status' => 'status#get_docbox_status'

    post 'status_drb' => 'status#status_drb'

    get "scanners/scan_info"

    post 'start_scanner' => 'scanners#start_scanner'
    post 'start_scanner_from_hardware' => 'scanners#start_scanner_from_hardware'
    post 'start_copy_from_hardware' => 'scanners#start_copy_from_hardware'
    post 'scan_error' =>  'scanners#scan_error'
    post 'scan_info' =>  'scanners#scan_info'

    resources :folders
    resources :tags
    resources :upload_sorting
    resources :documents
    resources :status
    resources :uploads

    root :to => 'search#search'

end

app/controllers/status_controller.rb
require 'Pusher'
class StatusController < ApplicationController
  before_action :accept_all_params
  skip_before_action :verify_authenticity_token
  include Pusher

#  skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }
  #http://stackoverflow.com/questions/9362910/rails-warning-cant-verify-csrf-token-authenticity-for-json-devise-requests

  # GET /status
  # GET /status.json
  def index

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  #### Clear Logfile, called from Status-Page
  def clear
    Log.clear_all
#    PrivatePub.publish_to "/status", :chat_message => "Hello, world!"
    redirect_to :action => :index
  end

  def start_conversion
    Page.clean_pending
    Converter.run_conversion(Page.for_batch_conversion)
    redirect_to :action => :index
  end

  def trigger_backup
    BackupJob.perform_later
    redirect_to :action => :index
  end


  ## called by the hardware stack to read the server status and to display if any error
  def get_server_status
    render :json => Log.check_errors?
  end

  def get_docbox_status
    status_summary = Page.status_hash
    error = ""
    if Log.check_errors?
      error = "ERR:"
    end
    message = error + "Up:#{status_summary[:upload]} Cv:#{status_summary[:convert]} OCR:#{status_summary[:pending_ocr]} S3:#{status_summary[:pending_backup]}"
    render :json => message
  end


  def accept_all_params
    params.permit!
  end


end

app/helpers/status_helper.rb
module StatusHelper
end

app/views/status/index.html.erb
<h1 xmlns="http://www.w3.org/1999/html">Status Information</h1>

</div>




<div class="status_frame">

  <h2>Converter / Scanners Connected</h2>

  <table>
    <tr>
      <th>Uid</th>
      <th>Service</th>
      <th>Prio</th>
      <th>Uri</th>
    </tr>

    <% Connector.all.each do |connection| %>
      <tr>
        <td><%= connection.uid %></td>
        <td><%= connection.service %></td>
        <td><%= connection.prio %></td>
        <td><%= connection.uri %></td>
      </tr>
    <% end %>
  </table>
  <br/>
  <%= button_to "Maintain Connections", connectors_path, :method => :get, :id => nil %>

</div>

<div class="status_frame">
  <h2>Documents not converted: <%= Page.uploading_status(:not_converted) %></h2>
  <h2>Documents pending conversion: <%= Page.uploading_status(:processing) %></h2>
  <% if Converter.connected? then %>
    <h2>Connected to remote Converter!</h2>
    <%= button_to "Trigger conversion & cleaning now ", status_start_conversion_path, :method => :get %>
  <% else %>
    <h2>Not connected !!!</h2>
  <% end %>
</div>


<div class="status_frame">
  <h2>Documents without
    backup: <%= Page.uploading_status(:no_backup) %> <%= button_to "Trigger backup now", trigger_backup_path, :method => :get if Page.uploading_status(:no_backup) > 0 %></h2>
  Documents not converted will not be uploaded to backup
</div>




<h1>Logfile</h1>



<div class="status_frame">

  </br>

  <%= button_to "Clear Logfile and Errors", status_clear_path, :method => :get %>

  </br>

  <table>
    <% Log.order('created_at desc').all.each do |log| %>
      <tr>
        <td style="border: 1px solid">
          <% if log.messagetype == Log::ERROR %>
            <p style="color:red">ERROR</p>
          <% else %>
            STATUS
          <% end %>
        </td>
        <td style="border: 1px solid">
          <%= log.created_at.localtime %>
        </td>
        <td style="border: 1px solid">
          <%= log.source %>
        </td>
        <td style="border: 1px solid">
          <%= log.message %>
        </td>
      </tr>
    <% end %>
  </table>
</div>